import typing
from .Names.LocationName import LocationName


class RegionName:
    Menu = "Menu"
    Central_Overworld = "Central Overworld"
    Central_Cyberworld = "Central Cyberworld"
    Central3_and_Underground = "Central3 and Underground"
    Seaside_Overworld = "Seaside Overworld"
    Seaside_Cyberworld = "Seaside Cyberworld"
    Green_Overworld = "Green Overworld"
    Green_Cyberworld = "Green Cyberworld"
    Sky_Overworld = "Sky Overworld"
    Sky_Cyberworld = "Sky Cyberworld"
    ACDC_Overworld = "ACDC Overworld"
    ACDC_Cyberworld = "ACDC Cyberworld"
    Undernet = "Undernet"
    Graveyard = "Graveyard"
    Expo = "Expo"


class RegionInfo:
    name: str
    connections: typing.List[str]
    locations: typing.List[str]

    def __init__(self, name, connections, locations):
        self.name = name
        self.connections = connections
        self.locations = locations


regions = [
    RegionInfo(RegionName.Menu, [RegionName.Central_Overworld], []),
    RegionInfo(RegionName.Central_Overworld,
               [RegionName.Central_Cyberworld, RegionName.Seaside_Overworld, RegionName.Green_Overworld, RegionName.Sky_Overworld, RegionName.ACDC_Overworld, RegionName.Expo],
               [
                    LocationName.Robot_Control_Comp_1_BMD_1,
                    LocationName.Robot_Control_Comp_1_BMD_2,
                    LocationName.Robot_Control_Comp_2_BMD_1,
                    LocationName.Robot_Control_Comp_2_BMD_2,
                    LocationName.RoboDog_Comp_BMD,
                    LocationName.Labs_Comp_1_BMD_1,
                    LocationName.Labs_Comp_1_BMD_2,
                    LocationName.Class_6_1_Comp_BMD_1,
                    LocationName.Class_6_1_Comp_BMD_2,
                    LocationName.Class_6_2_Comp_BMD,
                    LocationName.Class_1_1_Comp_BMD_1,
                    LocationName.Class_1_1_Comp_BMD_2,
                    LocationName.Class_1_2_Comp_BMD_1,
                    LocationName.Class_1_2_Comp_BMD_2,
                    LocationName.Bathroom_Comp_BMD,
                    LocationName.Security_Camera_Comp_BMD_1,
                    LocationName.Security_Camera_Comp_BMD_2,
                    LocationName.Labs_Comp_2_BMD,
                    LocationName.Teachers_Room_Comp_BMD_1,
                    LocationName.Teachers_Room_Comp_BMD_2,
                    LocationName.Monitor_Comp_BMD,
                    LocationName.Principals_Office_Comp_BMD_1,
                    LocationName.Principals_Office_Comp_BMD_2,
                    LocationName.Class_6_2_Comp_PMD,
                    LocationName.Labs_Comp_2_PMD,
                    LocationName.School_Mr_Quiz,
                    LocationName.Central_Barr100_H_Trade,
                    LocationName.Class_1_2_EnergBom_K_Trade,
                    LocationName.Class_6_1_Grid,
                    LocationName.Principals_Coffee_Table,
                    LocationName.Class_1_2_Heel_Navi,
                    LocationName.Talk_To_Mayl,
                    LocationName.EraseMan_Class,
                    LocationName.GroundMan_Class,
                    LocationName.RoboDog_Comp_Virus_Battler,
                    LocationName.Virus_Deletion,
                    LocationName.Find_Keepsake,
                    LocationName.Errand_Request,
                    LocationName.JuvenileDiv,
                    LocationName.Somebody_Help,
                    LocationName.DietGood_Money,
                    LocationName.Find_The_Virus,
                    LocationName.Get_The_Bad_Guy,
                    LocationName.Not_Engh_Member,
                    LocationName.Self_Research,
                    LocationName.Wheres_My_Navi,
                    LocationName.One_More_Time,
                    LocationName.Lotto_Code_01,
                    LocationName.Lotto_Code_02,
                    LocationName.Lotto_Code_03,
                    LocationName.Lotto_Code_04,
                    LocationName.Lotto_Code_05,
                    LocationName.Lotto_Code_06,
                    LocationName.Lotto_Code_07,
                    LocationName.Lotto_Code_08,
                    LocationName.Lotto_Code_09,
                    LocationName.Lotto_Code_10,
                    LocationName.Lotto_Code_11,
                    LocationName.Lotto_Code_12,
                    LocationName.Lotto_Code_13,
                    LocationName.Lotto_Code_14,
                    LocationName.Lotto_Code_15,
                    LocationName.Lotto_Code_16,
                    LocationName.Lotto_Code_17,
                    LocationName.Lotto_Code_18,
                    LocationName.Lotto_Code_19,
                    LocationName.Lotto_Code_20,
                    LocationName.Lotto_Code_21,
                    LocationName.Lotto_Code_22,
                    LocationName.Lotto_Code_23,
                    LocationName.Lotto_Code_24,
                    LocationName.Lotto_Code_25,
                    LocationName.Lotto_Code_26,
                    LocationName.Lotto_Code_27,
                    LocationName.Lotto_Code_28,
                    LocationName.Lotto_Code_29,
                    LocationName.Lotto_Code_30,
                    LocationName.Lotto_Code_31,
                    LocationName.Lotto_Code_32,
                    LocationName.Lotto_Code_33,
                    LocationName.Lotto_Code_34,
                    LocationName.Lotto_Code_35,
                    LocationName.Lotto_Code_36,
                    LocationName.Lotto_Code_37,
                    LocationName.Lotto_Code_38,
                    LocationName.Lotto_Code_39,
                    LocationName.Lotto_Code_40,
                    LocationName.Lotto_Code_41,
                    LocationName.Lotto_Code_42,
                    LocationName.Lotto_Code_43,
                    LocationName.Lotto_Code_44,
                    LocationName.Lotto_Code_45,
                    LocationName.Lotto_Code_46,
                    LocationName.Lotto_Code_47,
                    LocationName.Lotto_Code_48,
                    LocationName.Lotto_Code_49,
                    LocationName.Lotto_Code_50,
                    LocationName.Lotto_Code_51,
                    LocationName.Lotto_Code_52,
                    LocationName.Lotto_Code_53,
                    LocationName.Lotto_Code_54,
                    LocationName.Lotto_Code_55,
                    LocationName.Lotto_Code_56,
                    LocationName.Lotto_Code_57,
                    LocationName.Lotto_Code_58,
                    LocationName.ProtoMan_FZ
               ]),
    RegionInfo(RegionName.Central_Cyberworld,
               [RegionName.Central3_and_Underground],
               [
                    LocationName.Central_Area_1_BMD_1,
                    LocationName.Central_Area_1_BMD_2,
                    LocationName.Central_Area_2_BMD_1,
                    LocationName.Central_Area_2_BMD_2,
                    LocationName.Central_1_Net_Cafe,
                    LocationName.Central_2_Heel_Navi,
                    LocationName.Central_1_Virus_Battler,
                    LocationName.For_Victory,
                    LocationName.BlastMan_EX,
                    LocationName.BlastMan_SP,
               ]),
    RegionInfo(RegionName.Central3_and_Underground,
               [RegionName.Central_Cyberworld, RegionName.Seaside_Cyberworld, RegionName.Green_Cyberworld, RegionName.Sky_Cyberworld, RegionName.ACDC_Cyberworld],
               [
                    LocationName.Central_Area_3_BMD,
                    LocationName.Central_Area_3_PMD,
                    LocationName.Underground_2_BMD_1,
                    LocationName.Underground_2_BMD_2,
                    LocationName.Underground_1_PMD_1,
                    LocationName.Underground_1_PMD_2,
                    LocationName.CircusMan_EX,
                    LocationName.Colonel_EX,
                    LocationName.CircusMan_SP,
                    LocationName.Colonel_SP,
                    LocationName.Bass_BX
               ]),
    RegionInfo(RegionName.Seaside_Overworld,
               [RegionName.Seaside_Cyberworld, RegionName.Central_Overworld, RegionName.Green_Overworld, RegionName.Sky_Overworld, RegionName.ACDC_Overworld],
               [
                    LocationName.Aquarium_Comp_1_BMD_1,
                    LocationName.Aquarium_Comp_1_BMD_2,
                    LocationName.Aquarium_Comp_2_BMD_1,
                    LocationName.Aquarium_Comp_2_BMD_2,
                    LocationName.Aquarium_Comp_3_BMD_1,
                    LocationName.Aquarium_Comp_3_BMD_2,
                    LocationName.Fish_Stick_Shop_Comp_BMD_1,
                    LocationName.Fish_Stick_Shop_Comp_BMD_2,
                    LocationName.Vending_Machine_Comp_BMD_1,
                    LocationName.Vending_Machine_Comp_BMD_2,
                    LocationName.Water_Machine_Comp_BMD,
                    LocationName.Popcorn_Shop_Comp_BMD,
                    LocationName.Pipe_Comp_BMD,
                    LocationName.Aquarium_Quiz_Master,
                    LocationName.Aquarium_DublShot_C_Trade,
                    LocationName.WatrMchn_HiBoomer_V_Trade,
                    LocationName.Seaside_Auditorium_Trash_Can,
                    LocationName.Seaside_Control_Room_Ladder,
                    LocationName.Seaside_Auditorium_Man,
                    LocationName.Aquarium_Comp_1_Navi,
                    LocationName.ChargeMan_Class,
                    LocationName.DustMan_Class,
                    LocationName.Water_Machine_Comp_Virus_Battler,
                    LocationName.Stock_Up,
                    LocationName.PenguinsRanAway,
                    LocationName.Got_A_Problem,
                    LocationName.Cant_Open_Safe,
                    LocationName.Update_Help,
                    LocationName.Do_Something,
                    LocationName.Track_The_Crmnl_1,
                    LocationName.Track_The_Crmnl_2,
                    LocationName.Track_The_Crmnl_3,
                    LocationName.An_Experiment_1,
                    LocationName.An_Experiment_2,
                    LocationName.An_Experiment_3
               ]),
    RegionInfo(RegionName.Seaside_Cyberworld,
               [RegionName.Central3_and_Underground],
               [
                    LocationName.Aquarium_HP_BMD,
                    LocationName.Stuffed_Toy_Shop_Comp_BMD_1,
                    LocationName.Stuffed_Toy_Shop_Comp_BMD_2,
                    LocationName.Seaside_Area_1_BMD_1,
                    LocationName.Seaside_Area_1_BMD_2,
                    LocationName.Seaside_Area_1_BMD_3,
                    LocationName.Seaside_Area_2_BMD_1,
                    LocationName.Seaside_Area_2_BMD_2,
                    LocationName.Seaside_Area_2_BMD_3,
                    LocationName.Seaside_Area_3_BMD,
                    LocationName.Aquarium_HP_PMD,
                    LocationName.Seaside_Area_3_PMD,
                    LocationName.Aquarium_PnlRetrn_star_Trade,
                    LocationName.Get_The_Chip,
                    LocationName.StandIn_Recruit,
                    LocationName.DiveMan_EX,
                    LocationName.DiveMan_SP
               ]),
    RegionInfo(RegionName.Green_Overworld,
               [RegionName.Green_Cyberworld, RegionName.Central_Overworld, RegionName.Seaside_Overworld, RegionName.Sky_Overworld, RegionName.ACDC_Overworld],
               [
                    LocationName.JudgeTree_Comp_1_BMD_1,
                    LocationName.JudgeTree_Comp_1_BMD_2,
                    LocationName.JudgeTree_Comp_2_BMD_1,
                    LocationName.JudgeTree_Comp_2_BMD_2,
                    LocationName.JudgeTree_Comp_3_BMD_1,
                    LocationName.JudgeTree_Comp_3_BMD_2,
                    LocationName.Book_Comp_BMD_1,
                    LocationName.Book_Comp_BMD_2,
                    LocationName.Punish_Chair_Comp_BMD,
                    LocationName.Symbol_Comp_BMD_1,
                    LocationName.Symbol_Comp_BMD_2,
                    LocationName.Punish_Chair_Comp_PMD,
                    LocationName.Green_Quiz_King,
                    LocationName.Green_HolyPnl_S_Trade,
                    LocationName.Green_Foyer_Flowers,
                    LocationName.Green_Punishment_Room_Prog,
                    LocationName.SlashMan_Class,
                    LocationName.TenguMan_Class,
                    LocationName.Punish_Chair_Comp_Virus_Battler,
                    LocationName.Daughter_Worry,
                    LocationName.Stop_Him,
                    LocationName.TimeCpsl
               ]),
    RegionInfo(RegionName.Green_Cyberworld,
               [RegionName.Central3_and_Underground],
               [
                    LocationName.Green_HP_BMD,
                    LocationName.Green_Area_1_BMD_1,
                    LocationName.Green_Area_1_BMD_2,
                    LocationName.Green_Area_2_BMD_1,
                    LocationName.Green_Area_2_BMD_2,
                    LocationName.Green_Area_2_BMD_3,
                    LocationName.Undernet_Zero_BMD_3,
                    LocationName.Green_HP_PMD,
                    LocationName.Green_Area_1_PMD,
                    LocationName.Green_2_Net_Cafe,
                    LocationName.Green_1_Heel_Navi,
                    LocationName.Bass,
                    LocationName.Loan_Collection,
                    LocationName.Lumber_Merchant,
                    LocationName.RoadToSoulBtlr,
                    LocationName.JudgeMan_EX,
                    LocationName.JudgeMan_SP
               ]),
    RegionInfo(RegionName.Sky_Overworld,
               [RegionName.Sky_Cyberworld, RegionName.Central_Overworld, RegionName.Seaside_Overworld, RegionName.Green_Overworld, RegionName.ACDC_Overworld],
               [
                    LocationName.Mr_Weather_Comp_1_BMD_1,
                    LocationName.Mr_Weather_Comp_1_BMD_2,
                    LocationName.Mr_Weather_Comp_2_BMD_1,
                    LocationName.Mr_Weather_Comp_2_BMD_2,
                    LocationName.Mr_Weather_Comp_3_BMD_1,
                    LocationName.Mr_Weather_Comp_3_BMD_2,
                    LocationName.Elevator_Comp_BMD,
                    LocationName.Fan_Comp_BMD_1,
                    LocationName.Fan_Comp_BMD_2,
                    LocationName.Air_Conditioner_Comp_BMD_1,
                    LocationName.Air_Conditioner_Comp_BMD_2,
                    LocationName.Heater_Comp_BMD_1,
                    LocationName.Heater_Comp_BMD_2,
                    LocationName.Shower_Comp_BMD_1,
                    LocationName.Shower_Comp_BMD_2,
                    LocationName.Heliport_Comp_BMD_1,
                    LocationName.Heliport_Comp_BMD_2,
                    LocationName.Observation_Comp_BMD_1,
                    LocationName.Observation_Comp_BMD_2,
                    LocationName.Oxygen_Tank_Comp_BMD,
                    LocationName.Oxygen_Tank_Comp_PMD,
                    LocationName.AirCon_AuraHed1_B_Trade,
                    LocationName.Sky_GrabRvng_I_Trade,
                    LocationName.Sky_Air_Tank,
                    LocationName.ElecMan_Class,
                    LocationName.TomahawkMan_Class,
                    LocationName.Oxygen_Tank_Comp_Virus_Battler,
                    LocationName.OfficialRequest_1,
                    LocationName.OfficialRequest_2,
                    LocationName.OfficialRequest_3,
                    LocationName.SupportChip_Pls,
                    LocationName.Negotiate
               ]),
    RegionInfo(RegionName.Sky_Cyberworld,
               [RegionName.Central3_and_Underground, RegionName.Undernet],
               [
                    LocationName.Sky_HP_BMD,
                    LocationName.Sky_Area_1_BMD_1,
                    LocationName.Sky_Area_1_BMD_2,
                    LocationName.Sky_Area_2_BMD_1,
                    LocationName.Sky_Area_2_BMD_2,
                    LocationName.Sky_Area_2_BMD_3,
                    LocationName.Sky_HP_PMD,
                    LocationName.Sky_Area_1_PMD,
                    LocationName.Sky_1_Net_Cafe,
                    LocationName.Sky_1_Brown_Navi,
                    LocationName.Songwriter,
                    LocationName.Buy_Whch_Stock,
                    LocationName.Want_Meet_Dghtr,
                    LocationName.ElementMan_EX,
                    LocationName.ElementMan_SP
               ]),
    RegionInfo(RegionName.ACDC_Overworld,
               [RegionName.ACDC_Cyberworld, RegionName.Central_Overworld, RegionName.Seaside_Overworld, RegionName.Green_Overworld, RegionName.Sky_Overworld],
               [
                    LocationName.Dog_House_Comp_BMD_1,
                    LocationName.Dog_House_Comp_BMD_2,
                    LocationName.ACDC_Dexs_Door
               ]),
    RegionInfo(RegionName.ACDC_Cyberworld,
               [RegionName.Central3_and_Underground],
               [
                    LocationName.ACDC_HP_BMD,
                    LocationName.ACDC_Area_BMD_1,
                    LocationName.ACDC_Area_BMD_2,
                    LocationName.ACDC_HP_PMD,
                    LocationName.ACDC_Area_PMD,
                    LocationName.ACDC_BigBomb_O_Trade
               ]),
    RegionInfo(RegionName.Undernet,
               [RegionName.Sky_Cyberworld, RegionName.Graveyard],
               [
                    LocationName.Undernet_1_BMD,
                    LocationName.Undernet_Zero_BMD_1,
                    LocationName.Undernet_Zero_BMD_2,
                    LocationName.Undernet_2_BMD,
                    LocationName.Undernet_1_PMD,
                    LocationName.Undernet_2_PMD,
                    LocationName.Undernet_Zero_Heel_Navi
               ]),
    RegionInfo(RegionName.Graveyard,
               [RegionName.Undernet],
               [
                    LocationName.Graveyard_BMD_1,
                    LocationName.Graveyard_BMD_2,
                    LocationName.Graveyard_BMD_3,
                    LocationName.Graveyard_BMD_4,
                    LocationName.Graveyard_BMD_5,
                    LocationName.Graveyard_PMD_1,
                    LocationName.Graveyard_PMD_2,
                    LocationName.Bass_SP
               ]),
    RegionInfo(RegionName.Expo,
               [RegionName.Central_Overworld],
               [
                    LocationName.Pavilion_Comp_1_BMD_1,
                    LocationName.Pavilion_Comp_1_BMD_2,
                    LocationName.Pavilion_Comp_2_BMD_1,
                    LocationName.Pavilion_Comp_2_BMD_2,
                    LocationName.Pavilion_Comp_3_BMD_1,
                    LocationName.Pavilion_Comp_3_BMD_2,
                    LocationName.Pavilion_Comp_4_BMD_1,
                    LocationName.Pavilion_Comp_4_BMD_2,
                    LocationName.Mascot_Comp_BMD_1,
                    LocationName.Mascot_Comp_BMD_2,
                    LocationName.Guide_Panel_Comp_BMD,
                    LocationName.Seaside_Pavilion_Waterfall,
                    LocationName.Gregar_Defeated
               ])
]