from enum import Enum


class LocationName():
    ## Blue Mystery Data
    #
    Robot_Control_Comp_1_BMD_1 = "Robot Control Comp 1 BMD 1"
    Robot_Control_Comp_1_BMD_2 = "Robot Control Comp 1 BMD 2"
    Robot_Control_Comp_2_BMD_1 = "Robot Control Comp 2 BMD 1"
    Robot_Control_Comp_2_BMD_2 = "Robot Control Comp 2 BMD 2"

    #
    Aquarium_Comp_1_BMD_1 = "Aquarium Comp 1 BMD 1"
    Aquarium_Comp_1_BMD_2 = "Aquarium Comp 1 BMD 2"
    Aquarium_Comp_2_BMD_1 = "Aquarium Comp 2 BMD 1"
    Aquarium_Comp_2_BMD_2 = "Aquarium Comp 2 BMD 2"
    Aquarium_Comp_3_BMD_1 = "Aquarium Comp 3 BMD 1"
    Aquarium_Comp_3_BMD_2 = "Aquarium Comp 3 BMD 2"

    #
    JudgeTree_Comp_1_BMD_1 = "JudgeTree Comp 1 BMD 1"
    JudgeTree_Comp_1_BMD_2 = "JudgeTree Comp 1 BMD 2"
    JudgeTree_Comp_2_BMD_1 = "JudgeTree Comp 2 BMD 1"
    JudgeTree_Comp_2_BMD_2 = "JudgeTree Comp 2 BMD 2"
    JudgeTree_Comp_3_BMD_1 = "JudgeTree Comp 3 BMD 1"
    JudgeTree_Comp_3_BMD_2 = "JudgeTree Comp 3 BMD 2"

    #
    Mr_Weather_Comp_1_BMD_1 = "Mr. Weather Comp 1 BMD 1"
    Mr_Weather_Comp_1_BMD_2 = "Mr. Weather Comp 1 BMD 2"
    Mr_Weather_Comp_2_BMD_1 = "Mr. Weather Comp 2 BMD 1"
    Mr_Weather_Comp_2_BMD_2 = "Mr. Weather Comp 2 BMD 2"
    Mr_Weather_Comp_3_BMD_1 = "Mr. Weather Comp 3 BMD 1"
    Mr_Weather_Comp_3_BMD_2 = "Mr. Weather Comp 3 BMD 2"

    #
    Pavilion_Comp_1_BMD_1 = "Pavilion Comp 1 BMD 1"
    Pavilion_Comp_1_BMD_2 = "Pavilion Comp 1 BMD 2"
    Pavilion_Comp_2_BMD_1 = "Pavilion Comp 2 BMD 1"
    Pavilion_Comp_2_BMD_2 = "Pavilion Comp 2 BMD 2"
    Pavilion_Comp_3_BMD_1 = "Pavilion Comp 3 BMD 1"
    Pavilion_Comp_3_BMD_2 = "Pavilion Comp 3 BMD 2"
    Pavilion_Comp_4_BMD_1 = "Pavilion Comp 4 BMD 1"
    Pavilion_Comp_4_BMD_2 = "Pavilion Comp 4 BMD 2"

    #
    ACDC_HP_BMD = "ACDC HP BMD"
    Aquarium_HP_BMD = "Aquarium HP BMD"
    Green_HP_BMD = "Green HP BMD"
    Sky_HP_BMD = "Sky HP BMD"

    #
    RoboDog_Comp_BMD = "RoboDog Comp BMD"
    Labs_Comp_1_BMD_1 = "Lab's Comp 1 BMD 1"
    Labs_Comp_1_BMD_2 = "Lab's Comp 1 BMD 2"
    Class_6_1_Comp_BMD_1 = "Class 6-1 Comp BMD 1"
    Class_6_1_Comp_BMD_2 = "Class 6-1 Comp BMD 2"
    Class_6_2_Comp_BMD = "Class 6-2 Comp BMD"
    Class_1_1_Comp_BMD_1 = "Class 1-1 Comp BMD 1"
    Class_1_1_Comp_BMD_2 = "Class 1-1 Comp BMD 2"
    Class_1_2_Comp_BMD_1 = "Class 1-2 Comp BMD 1"
    Class_1_2_Comp_BMD_2 = "Class 1-2 Comp BMD 2"
    Bathroom_Comp_BMD = "Bathroom Comp BMD"
    Elevator_Comp_BMD = "Elevator Comp BMD"
    Fish_Stick_Shop_Comp_BMD_1 = "Fish Stick Shop Comp BMD 1"
    Fish_Stick_Shop_Comp_BMD_2 = "Fish Stick Shop Comp BMD 2"
    Security_Camera_Comp_BMD_1 = "Security Camera Comp BMD 1"
    Security_Camera_Comp_BMD_2 = "Security Camera Comp BMD 2"
    Book_Comp_BMD_1 = "Book Comp BMD 1"
    Book_Comp_BMD_2 = "Book Comp BMD 2"
    Fan_Comp_BMD_1 = "Fan Comp BMD 1"
    Fan_Comp_BMD_2 = "Fan Comp BMD 2"
    Air_Conditioner_Comp_BMD_1 = "Air Conditioner Comp BMD 1"
    Air_Conditioner_Comp_BMD_2 = "Air Conditioner Comp BMD 2"
    Heater_Comp_BMD_1 = "Heater Comp BMD 1"
    Heater_Comp_BMD_2 = "Heater Comp BMD 2"
    Shower_Comp_BMD_1 = "Shower Comp BMD 1"
    Shower_Comp_BMD_2 = "Shower Comp BMD 2"
    Heliport_Comp_BMD_1 = "Heliport Comp BMD 1"
    Heliport_Comp_BMD_2 = "Heliport Comp BMD 2"
    Labs_Comp_2_BMD = "Lab's Comp 2 BMD"
    Vending_Machine_Comp_BMD_1 = "Vending Machine Comp BMD 1"
    Vending_Machine_Comp_BMD_2 = "Vending Machine Comp BMD 2"
    Punish_Chair_Comp_BMD = "Punish Chair Comp BMD"
    Water_Machine_Comp_BMD = "Water Machine Comp BMD"
    Symbol_Comp_BMD_1 = "Symbol Comp BMD 1"
    Symbol_Comp_BMD_2 = "Symbol Comp BMD 2"
    Monitor_Comp_BMD = "Monitor Comp BMD"
    Popcorn_Shop_Comp_BMD = "Popcorn Shop Comp BMD"
    Teachers_Room_Comp_BMD_1 = "Teachers' Room Comp BMD 1"
    Teachers_Room_Comp_BMD_2 = "Teachers' Room Comp BMD 2"
    Pipe_Comp_BMD = "Pipe Comp BMD"
    Observation_Comp_BMD_1 = "Observation Comp BMD 1"
    Observation_Comp_BMD_2 = "Observation Comp BMD 2"
    Oxygen_Tank_Comp_BMD = "Oxygen Tank Comp BMD"
    Principals_Office_Comp_BMD_1 = "Principal's Office Comp BMD 1"
    Principals_Office_Comp_BMD_2 = "Principal's Office Comp BMD 2"
    Mascot_Comp_BMD_1 = "Mascot Comp BMD 1"
    Mascot_Comp_BMD_2 = "Mascot Comp BMD 2"
    Stuffed_Toy_Shop_Comp_BMD_1 = "Stuffed Toy Shop Comp BMD 1"
    Stuffed_Toy_Shop_Comp_BMD_2 = "Stuffed Toy Shop Comp BMD 2"
    Dog_House_Comp_BMD_1 = "Dog House Comp BMD 1"
    Dog_House_Comp_BMD_2 = "Dog House Comp BMD 2"
    Guide_Panel_Comp_BMD = "Guide Panel Comp BMD"

    #
    Central_Area_1_BMD_1 = "Central Area 1 BMD 1"
    Central_Area_1_BMD_2 = "Central Area 1 BMD 2"
    Central_Area_2_BMD_1 = "Central Area 2 BMD 1"
    Central_Area_2_BMD_2 = "Central Area 2 BMD 2"
    Central_Area_3_BMD = "Central Area 3 BMD"

    #
    Seaside_Area_1_BMD_1 = "Seaside Area 1 BMD 1"
    Seaside_Area_1_BMD_2 = "Seaside Area 1 BMD 2"
    Seaside_Area_1_BMD_3 = "Seaside Area 1 BMD 3"
    Seaside_Area_2_BMD_1 = "Seaside Area 2 BMD 1"
    Seaside_Area_2_BMD_2 = "Seaside Area 2 BMD 2"
    Seaside_Area_2_BMD_3 = "Seaside Area 2 BMD 3"
    Seaside_Area_3_BMD = "Seaside Area 3 BMD"

    #
    Green_Area_1_BMD_1 = "Green Area 1 BMD 1"
    Green_Area_1_BMD_2 = "Green Area 1 BMD 2"
    Green_Area_2_BMD_1 = "Green Area 2 BMD 1"
    Green_Area_2_BMD_2 = "Green Area 2 BMD 2"
    Green_Area_2_BMD_3 = "Green Area 2 BMD 3"

    #
    Underground_2_BMD_1 = "Underground 2 BMD 1"
    Underground_2_BMD_2 = "Underground 2 BMD 2"

    #
    Sky_Area_1_BMD_1 = "Sky Area 1 BMD 1"
    Sky_Area_1_BMD_2 = "Sky Area 1 BMD 2"
    Sky_Area_2_BMD_1 = "Sky Area 2 BMD 1"
    Sky_Area_2_BMD_2 = "Sky Area 2 BMD 2"
    Sky_Area_2_BMD_3 = "Sky Area 2 BMD 3"

    #
    ACDC_Area_BMD_1 = "ACDC Area BMD 1"
    ACDC_Area_BMD_2 = "ACDC Area BMD 2"

    #
    Undernet_1_BMD = "Undernet 1 BMD"
    Undernet_Zero_BMD_1 = "Undernet Zero BMD 1"
    Undernet_Zero_BMD_2 = "Undernet Zero BMD 2"
    Undernet_Zero_BMD_3 = "Undernet Zero BMD 3"
    Undernet_2_BMD = "Undernet 2 BMD"

    #
    Graveyard_BMD_1 = "Graveyard BMD 1"
    Graveyard_BMD_2 = "Graveyard BMD 2"
    Graveyard_BMD_3 = "Graveyard BMD 3"
    Graveyard_BMD_4 = "Graveyard BMD 4"
    Graveyard_BMD_5 = "Graveyard BMD 5"

    ## Purple Mystery Data
    ACDC_HP_PMD = "ACDC HP PMD"
    Aquarium_HP_PMD = "Aquarium HP PMD"
    Green_HP_PMD = "Green HP PMD"
    Sky_HP_PMD = "Sky HP PMD"
    Class_6_2_Comp_PMD = "Class 6-2 Comp PMD"
    Labs_Comp_2_PMD = "Lab's Comp 2 PMD"
    Punish_Chair_Comp_PMD = "Punish Chair Comp PMD"
    Oxygen_Tank_Comp_PMD = "Oxygen Tank Comp PMD"
    Central_Area_3_PMD = "Central Area 3 PMD"
    Seaside_Area_3_PMD = "Seaside Area 3 PMD"
    Green_Area_1_PMD = "Green Area 1 PMD"
    Underground_1_PMD_1 = "Underground 1 PMD 1"
    Underground_1_PMD_2 = "Underground 1 PMD 2"
    Sky_Area_1_PMD = "Sky Area 1 PMD"
    ACDC_Area_PMD = "ACDC Area PMD"
    Undernet_1_PMD = "Undernet 1 PMD"
    Undernet_2_PMD = "Undernet 2 PMD"
    Graveyard_PMD_1 = "Graveyard PMD 1"
    Graveyard_PMD_2 = "Graveyard PMD 2"

    ## Overworld Items
    School_Mr_Quiz = "School Mr Quiz"
    Aquarium_Quiz_Master = "Aquarium Quiz Master"
    Green_Quiz_King = "Green Quiz King"
    Central_Barr100_H_Trade = "Central Barr100 H Trade"
    Aquarium_PnlRetrn_*_Trade = "Aquarium PnlRetrn * Trade"
    Green_HolyPnl_S_Trade = "Green HolyPnl S Trade"
    AirCon_AuraHed1_B_Trade = "AirCon AuraHed1 B Trade"
    Class_1_2_EnergBom_K_Trade = "Class 1-2 EnergBom K Trade"
    Aquarium_DublShot_C_Trade = "Aquarium DublShot C Trade"
    WatrMchn_HiBoomer_V_Trade = "WatrMchn HiBoomer V Trade"
    Sky_GrabRvng_I_Trade = "Sky GrabRvng I Trade"
    ACDC_BigBomb_O_Trade = "ACDC BigBomb O Trade"
    Class_6_1_Grid = "Class 6-1 Grid"
    Seaside_Auditorium_Trash_Can = "Seaside Auditorium Trash Can"
    Seaside_Control_Room_Ladder = "Seaside Control Room Ladder"
    Green_Foyer_Flowers = "Green Foyer Flowers"
    Sky_Air_Tank = "Sky Air Tank"
    ACDC_Dexs_Door = "ACDC Dexs Door"
    Principals_Coffee_Table = "Principal's Coffee Table"
    Seaside_Pavilion_Waterfall = "Seaside Pavilion Waterfall"
    Central_1_Net_Cafe = "Central 1 Net Cafe"
    Green_2_Net_Cafe = "Green 2 Net Cafe"
    Sky_1_Net_Cafe = "Sky 1 Net Cafe"
    Central_2_Heel_Navi = "Central 2 Heel Navi"
    Class_1_2_Heel_Navi = "Class 1-2 Heel Navi"
    Seaside_Auditorium_Man = "Seaside Auditorium Man"
    Aquarium_Comp_1_Navi = "Aquarium Comp 1 Navi"
    Green_1_Heel_Navi = "Green 1 Heel Navi"
    Undernet_0_Heel_Navi = "Undernet 0 Heel Navi"
    Green_Punishment_Room_Prog = "Green Punishment Room Prog"
    Sky_1_Brown_Navi = "Sky 1 Brown Navi"
    Bass = "Bass"
    Talk_To_Mayl = "Talk To Mayl"
    
    ## Requests
    Virus_Deletion = "Request: Virus Deletion"
    Find_Keepsake = "Request: Find Keepsake"
    Errand_Request = "Request: Errand Request"
    For_Victory = "Request: For Victory!"
    JuvenileDiv = "Request: JuvenileDiv"
    Somebody_Help = "Request: Somebody Help!"
    Get_The_Chip = "Request: Get The Chip!"
    Stock_Up = "Request: Stock Up!"
    StandIn_Recruit = "Request: StandIn Recruit"
    PenguinsRanAway = "Request: PenguinsRanAway"
    Daughter_Worry = "Request: Daughter Worry"
    Stop_Him = "Request: Stop Him!"
    Loan_Collection = "Request: Loan Collection"
    Lumber_Merchant = "Request: Lumber Merchant"
    TimeCpsl = "Request: TimeCpsl"
    DietGood_Money = "Request: DietGood Money"
    Find_The_Virus = "Request: Find The Virus!"
    Got_A_Problem = "Request: Got A Problem."
    Songwriter = "Request: Songwriter"
    Buy_Whch_Stock = "Request: Buy Whch Stock?"
    Cant_Open_Safe = "Request: Can't Open Safe"
    Get_The_Bad_Guy = "Request: Get The Bad Guy"
    Update_Help = "Request: Update Help"
    Do_Something = "Request: Do Something!"
    Want_Meet_Dghtr = "Request: Want Meet Dghtr"
    Not_Engh_Member = "Request: Not Engh Member"
    Track_The_Crmnl_1 = "Request: Track The Crmnl - Reward 1"
    Track_The_Crmnl_2 = "Request: Track The Crmnl - Reward 2"
    Track_The_Crmnl_3 = "Request: Track The Crmnl - Reward 3"
    Self_Research = "Request: Self Research"
    OfficialRequest_1 = "Request: OfficialRequest - Reward 1"
    OfficialRequest_2 = "Request: OfficialRequest - Reward 2"
    OfficialRequest_3 = "Request: OfficialRequest - Reward 3"
    Wheres_My_Navi = "Request: Where's My Navi"
    One_More_Time = "Request: One More Time."
    SupportChip_Pls = "Request: SupportChip Pls"
    Negotiate = "Request: Negotiate!"
    An_Experiment_1 = "Request: An Experiment! - Reward 1"
    An_Experiment_2 = "Request: An Experiment! - Reward 2"
    An_Experiment_3 = "Request: An Experiment! - Reward 3"
    RoadToSoulBtlr = "Request: RoadToSoulBtlr!"

    ## Lotto Codes
    Lotto_Code_01 = "Lotto Code 01"
    Lotto_Code_02 = "Lotto Code 02"
    Lotto_Code_03 = "Lotto Code 03"
    Lotto_Code_04 = "Lotto Code 04"
    Lotto_Code_05 = "Lotto Code 05"
    Lotto_Code_06 = "Lotto Code 06"
    Lotto_Code_07 = "Lotto Code 07"
    Lotto_Code_08 = "Lotto Code 08"
    Lotto_Code_09 = "Lotto Code 09"
    Lotto_Code_10 = "Lotto Code 10"
    Lotto_Code_11 = "Lotto Code 11"
    Lotto_Code_12 = "Lotto Code 12"
    Lotto_Code_13 = "Lotto Code 13"
    Lotto_Code_14 = "Lotto Code 14"
    Lotto_Code_15 = "Lotto Code 15"
    Lotto_Code_16 = "Lotto Code 16"
    Lotto_Code_17 = "Lotto Code 17"
    Lotto_Code_18 = "Lotto Code 18"
    Lotto_Code_19 = "Lotto Code 19"
    Lotto_Code_20 = "Lotto Code 20"
    Lotto_Code_21 = "Lotto Code 21"
    Lotto_Code_22 = "Lotto Code 22"
    Lotto_Code_23 = "Lotto Code 23"
    Lotto_Code_24 = "Lotto Code 24"
    Lotto_Code_25 = "Lotto Code 25"
    Lotto_Code_26 = "Lotto Code 26"
    Lotto_Code_27 = "Lotto Code 27"
    Lotto_Code_28 = "Lotto Code 28"
    Lotto_Code_29 = "Lotto Code 29"
    Lotto_Code_30 = "Lotto Code 30"
    Lotto_Code_31 = "Lotto Code 31"
    Lotto_Code_32 = "Lotto Code 32"
    Lotto_Code_33 = "Lotto Code 33"
    Lotto_Code_34 = "Lotto Code 34"
    Lotto_Code_35 = "Lotto Code 35"
    Lotto_Code_36 = "Lotto Code 36"
    Lotto_Code_37 = "Lotto Code 37"
    Lotto_Code_38 = "Lotto Code 38"
    Lotto_Code_39 = "Lotto Code 39"
    Lotto_Code_40 = "Lotto Code 40"
    Lotto_Code_41 = "Lotto Code 41"
    Lotto_Code_42 = "Lotto Code 42"
    Lotto_Code_43 = "Lotto Code 43"
    Lotto_Code_44 = "Lotto Code 44"
    Lotto_Code_45 = "Lotto Code 45"
    Lotto_Code_46 = "Lotto Code 46"
    Lotto_Code_47 = "Lotto Code 47"
    Lotto_Code_48 = "Lotto Code 48"
    Lotto_Code_49 = "Lotto Code 49"
    Lotto_Code_50 = "Lotto Code 50"
    Lotto_Code_51 = "Lotto Code 51"
    Lotto_Code_52 = "Lotto Code 52"
    Lotto_Code_53 = "Lotto Code 53"
    Lotto_Code_54 = "Lotto Code 54"
    Lotto_Code_55 = "Lotto Code 55"
    Lotto_Code_56 = "Lotto Code 56"
    Lotto_Code_57 = "Lotto Code 57"
    Lotto_Code_58 = "Lotto Code 58"
    
    ## Bosses
    BlastMan_EX = "BlastMan EX"
    DiveMan_EX = "DiveMan EX"
    CircusMan_EX = "CircusMan EX"
    JudgeMan_EX = "JudgeMan EX"
    ElementMan_EX = "ElementMan EX"
    Colonel_EX = "Colonel EX"
    BlastMan_SP = "BlastMan SP"
    DiveMan_SP = "DiveMan SP"
    CircusMan_SP = "CircusMan SP"
    JudgeMan_SP = "JudgeMan SP"
    ElementMan_SP = "ElementMan SP"
    Colonel_SP = "Colonel SP"
